# Generated by Django 6.0.1 on 2026-01-07 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=15, unique=True)),
                ('name', models.TextField()),
                ('year', models.IntegerField()),
                ('planned_month', models.DateField()),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('fully_implemented_by', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('retired', models.BooleanField(default=False)),
                ('technical_report_available', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cluster')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.currency')),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.funder')),
                ('responsible_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.activitystatus')),
            ],
        ),
    ]
