# Generated by Django 6.0.1 on 2026-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('activities', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='funder',
        ),
        migrations.AddField(
            model_name='activity',
            name='clusters',
            field=models.ManyToManyField(blank=True, related_name='activities', to='accounts.cluster'),
        ),
        migrations.AddField(
            model_name='activity',
            name='funders',
            field=models.ManyToManyField(blank=True, related_name='activities', to='masters.funder'),
        ),
    ]
