# Generated by Django 6.0.1 on 2026-01-10 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activity_cluster_remove_activity_funder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('report', 'Technical Report'), ('proposal', 'Proposal Document'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('other', 'Other Document')], default='report', max_length=50)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('other', 'Other')], max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('is_latest', models.BooleanField(default=True, help_text='Indicates if this is the latest version')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for version control')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['activity', 'is_latest'], name='activities__activit_3bf950_idx'), models.Index(fields=['document_type', 'is_deleted'], name='activities__documen_d60465_idx'), models.Index(fields=['uploaded_at'], name='activities__uploade_215748_idx')],
            },
        ),
    ]
