# Generated by Django 6.0.1 on 2026-01-10 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_assignment', models.BooleanField(default=True)),
                ('notify_on_status_change', models.BooleanField(default=True)),
                ('notify_on_due_date_alert', models.BooleanField(default=True)),
                ('notify_on_activity_update', models.BooleanField(default=True)),
                ('notify_on_comment', models.BooleanField(default=True)),
                ('email_immediately', models.BooleanField(default=True)),
                ('email_daily_digest', models.BooleanField(default=False)),
                ('email_weekly_digest', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text="Don't send emails before this time", null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text="Don't send emails after this time", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'Activity Assignment'), ('status_change', 'Status Change'), ('due_date_alert', 'Due Date Alert'), ('update', 'Activity Update'), ('comment', 'New Comment')], default='update', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activities.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity', 'recipient'], name='activities__activit_152f8a_idx'), models.Index(fields=['status', 'created_at'], name='activities__status_acb1cf_idx'), models.Index(fields=['notification_type'], name='activities__notific_d716d8_idx')],
            },
        ),
    ]
