# Generated by Django 6.0.1 on 2026-01-13 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('activities', '0004_notificationpreference_notificationlog'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-year', 'activity_id']},
        ),
        migrations.AddField(
            model_name='activity',
            name='generated_from_recurrence',
            field=models.BooleanField(default=False, help_text='True if this activity was auto-generated from a recurring template'),
        ),
        migrations.AddField(
            model_name='activity',
            name='has_partial_procurement',
            field=models.BooleanField(default=False, help_text='Auto-set to True if procurement_amount is set and < total_budget'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_procurement',
            field=models.BooleanField(default=False, help_text='True if this entire activity is a procurement'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Mark if this activity repeats on a schedule'),
        ),
        migrations.AddField(
            model_name='activity',
            name='parent_activity',
            field=models.ForeignKey(blank=True, help_text='If this is a recurring instance, references the template/parent activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='procurement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of total budget allocated to procurement (leave blank if no procurement)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='procurement_type',
            field=models.CharField(blank=True, choices=[('equipment', 'Equipment'), ('services', 'Services'), ('supplies', 'Supplies'), ('venue', 'Venue/Logistics'), ('staff', 'Staff'), ('other', 'Other')], default='equipment', help_text='Type of procurement', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Stop generating instances after this date; leave blank for indefinite', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrence_interval',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Repeat every N periods (e.g., every 1 month, every 2 quarters)', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annual', 'Bi-Annual (every 6 months)'), ('annual', 'Annual')], default='monthly', help_text='Pattern for recurring activities', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_recurring'], name='activities__is_recu_2e4401_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_procurement'], name='activities__is_proc_90253d_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['parent_activity'], name='activities__parent__a29af9_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['recurrence_end_date'], name='activities__recurre_479564_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['year', 'planned_month'], name='activities__year_3dfddb_idx'),
        ),
    ]
