# Generated by Django 6.0.1 on 2026-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='procurement_breakdowns',
            field=models.JSONField(blank=True, help_text='Detailed breakdown of procurement items: [{type, amount, description}, ...]', null=True),
        ),
    ]
