# Generated by Django 6.0.1 on 2026-01-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_procurement_breakdowns'),
        ('masters', '0002_procurementtype'),
    ]

    operations = [
        # Step 1: Rename old field to temporary name
        migrations.RenameField(
            model_name='activity',
            old_name='procurement_type',
            new_name='procurement_type_old',
        ),
        # Step 2: Add new ForeignKey field as nullable
        migrations.AddField(
            model_name='activity',
            name='procurement_type',
            field=models.ForeignKey(
                blank=True,
                help_text='Type of procurement',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='masters.procurementtype'
            ),
        ),
    ]
