# Generated by Django 6.0.1 on 2026-01-24 10:16

from django.db import migrations


def migrate_procurement_types(apps, schema_editor):
    """Migrate old string procurement types to new ForeignKey"""
    Activity = apps.get_model('activities', 'Activity')
    ProcurementType = apps.get_model('masters', 'ProcurementType')
    
    # Create mapping from old string values to ProcurementType objects
    type_mapping = {}
    for ptype in ProcurementType.objects.all():
        type_mapping[ptype.code] = ptype
    
    # Update all activities
    updated_count = 0
    for activity in Activity.objects.all():
        if activity.procurement_type_old:
            old_value = activity.procurement_type_old
            if old_value in type_mapping:
                activity.procurement_type = type_mapping[old_value]
                activity.save(update_fields=['procurement_type'])
                updated_count += 1
    
    print(f"Migrated {updated_count} activities to new procurement types")


def reverse_migration(apps, schema_editor):
    """Reverse migration - copy ForeignKey back to string"""
    Activity = apps.get_model('activities', 'Activity')
    
    for activity in Activity.objects.all():
        if activity.procurement_type:
            activity.procurement_type_old = activity.procurement_type.code
            activity.save(update_fields=['procurement_type_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_procurement_type_field'),
        ('masters', '0002_procurementtype'),
    ]

    operations = [
        migrations.RunPython(migrate_procurement_types, reverse_migration),
    ]
