# Generated by Django 6.0.1 on 2026-01-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_migrate_procurement_type_data'),
    ]

    operations = [
        # Remove the old field
        migrations.RemoveField(
            model_name='activity',
            name='procurement_type_old',
        ),
    ]
