# Generated by Django 6.0.1 on 2026-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_remove_procurement_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='procurement_type_old',
            field=models.CharField(blank=True, help_text='Old procurement type field (temporary during migration)', max_length=20, null=True),
        ),
    ]
